# Generated by Django 4.2.10 on 2024-02-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('lbs', 'Pounds'), ('oz', 'Ounce')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
