# Generated by Django 4.2.10 on 2024-02-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('lbs', 'Pounds'), ('oz', 'Ounce'), ('ltr', 'Liters'), ('no', 'Unit')], max_length=10),
        ),
    ]
